### PR TITLE
staging: Add r-dearseq

### PR DESCRIPTION
**Pull request by mschilli87**
@rekado: Since this is the first time I am packaging a Bioconductor package, I wanted to run it by you.

### CODE REVIEW

**Comment by mschilli87** [comment]
rebased on latest master

**Comment by rekado** [comment]
Thanks for the patch!

I prefer to add these things straight to Guix proper.  I'll change the URI to use the `bioconductor-uri` procedure, and I'll change the first sentence of the description to make it a complete sentence.

**Comment by rekado** [comment]
Pushed to Guix `master` branch with commit 531a69ecb6ac85d03230d242b739c9671c984d0a.  Thanks!

**Comment by mschilli87** [comment]
@rekado:
> I prefer to add these things straight to Guix proper. I'll change the URI to use the `bioconductor-uri` procedure, and I'll change the first sentence of the description to make it a complete sentence.

Thank you for the support. I didn't submit sth hacky to Guix proper, so your `bioconductor-uri` fix is exactly the kind of thing why I came here. :wink:

**Pull request closed without merging**
